#!/bin/bash

# Exit on failure
set -e

C_BOLD_HEADER='\033[1m\033[95m'
C_BOLD_SUCCESS='\033[1m\033[92m'
C_END='\033[0m'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function ask_continue(){
    read -p "Do you want to continue? [y/n] " choice
    case "$choice" in
      y|Y ) ;;
      n|N ) exit;;
      * ) echo "Invalid choice."; exit 1;
    esac
}

function request_install_dependencies() {
    # Ask for confirmation

    echo -e "${C_BOLD_SUCCESS}🚀 Hey ${SUDO_USER}, let's setup your system!${C_END}"
    echo -e "${C_BOLD_HEADER}First we need your approval to update ...${C_END}"
    echo '$ apt-get -y -qq update && apt-get -y -qq upgrade'
    echo -e "${C_BOLD_HEADER}... and to install these required dependencies:${C_END}"
    echo '$ apt-get -y -qq install python3 python3-pip simpleflock'
    echo '$ pip3 -qq install click ruamel.yaml schema progressbar2 requests'
    echo -e "${C_BOLD_HEADER}Then we will perform your setup instructions.${C_END}"

    ask_continue

    # Update and install requirements
    echo -e "${C_BOLD_HEADER}This may take some time. Please wait.${C_END}"

    sudo apt-get -y -qq update && sudo apt-get -y -qq upgrade
    sudo apt-get -y -qq install python3 python3-pip
    sudo pip3 -qq install click ruamel.yaml schema progressbar2 requests simpleflock

    echo -e "${C_BOLD_SUCCESS}✓ Requirements installed!${C_END}"
}


# Check for requirements
check_command='import click, ruamel.yaml, schema, progressbar, requests, simpleflock'

if ! python3 -c "${check_command}" &> /dev/null; then
    request_install_dependencies
fi

# Perform setup

python3 ${DIR}/main.py $@
