#!/bin/bash

# Exit on failure
set -e

C_BOLD_HEADER='\033[1m\033[95m'
C_BOLD_SUCCESS='\033[1m\033[92m'
C_END='\033[0m'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function ask_continue(){
    read -p "Do you want to continue? [y/n] " choice
    case "$choice" in
      y|Y ) ;;
      n|N ) exit;;
      * ) echo "Invalid choice."; exit 1;
    esac
}

# Require root access
if [ "$UID" -ne 0 ]; then
    exec sudo "$0" "$@"
fi

# Ask for confirmation
echo -e "${C_BOLD_SUCCESS}🚀 Hey ${SUDO_USER}, let's setup your system!${C_END}"

echo -e "${C_BOLD_HEADER}First we need your approval to update ...${C_END}"

echo '$ apt-get -y -q update && apt-get -y -q upgrade'

echo -e "${C_BOLD_HEADER}... and to install these required dependencies:${C_END}"

echo '$ apt-get -y -q install python3 \
                        python3-click \
                        python3-yaml \
                        python3-schema'

echo -e "${C_BOLD_HEADER}Then we will perform your setup instructions.${C_END}"

ask_continue

# Update and install requirements

echo -e "${C_BOLD_HEADER}This may take some time. Please wait.${C_END}"

apt-get -y -q update && apt-get -y -q upgrade

apt-get -y -q install python3 \
                      python3-click \
                      python3-yaml \
                      python3-schema

# Perform setup

sudo -E -u "$SUDO_USER" python3 ${DIR}/main.py $@

echo -e "${C_BOLD_SUCCESS}✓ Setup completed. Have fun!${C_END}"
